### ISSUE TITLE
Add tab for Sister Chapter Link

### ISSUE THREAD

**Issue by victorchiew** [UBCEnvision/UBCEnvision.github.io#279]
Need to help feature Sister Chapter more prominently, instead of just a link to their website but a dedicated tab? What other ways can this be improved?

**Comment by csianglim** [comment]
Recommend putting a 'Sister Chapter' blurb in the about page

**Comment by Corneliuscob** [comment]
you could have it under the title as well.

UBC Envision
The Ubb AiChe Student Chapter,
In partnership/sisterhood with Barcelona's UPC

Or pin the Sister chapter on top of new center
