### ISSUE TITLE
Mathjax for latex equation rendering is broken

### ISSUE THREAD

**Issue by csianglim** [UBCEnvision/UBCEnvision.github.io#302]
Fix mathjax for rendering latex.

Equations in https://www.ubcenvision.com/blog/2017/02/28/fuelcell.html such as $$ ∂P = \left(\frac{RTV}{(V - nb)^2} - \frac{2na}{V^2}\right) \times ∂n $$ are not rendering properly.

The old website shows what it should look like. http://www.ubcchemecar.com/blog/2017/02/28/fuelcell/

Make sure the mathjax script is loaded correctly: https://www.mathjax.org

**Comment by kurisam** [comment]
from what i've read this tag fixes the issue if included on each page that uses mathjax commands (tested locally on the fuel cell article ): 
```
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML' async></script>
```

but i don't know if there's a better way of fixing it other than that

**Comment by csianglim** [comment]
Try adding the new link in the mathjax include file: https://github.com/UBCEnvision/UBCEnvision.github.io/blob/aafd5b2b71b3517ffb66ba2a573b4923d5012043/_includes/mathjax.html
