### ISSUE TITLE
Instagram feed not showing on landing

### ISSUE THREAD

**Issue by dzh-ad** [UBCEnvision/UBCEnvision.github.io#338]

**Comment by jd4900** [comment]
Going to need access to the intagram account for this one @mcassol . Seems like the credentials are out of date. 

```javascript
Uncaught Error: Error from Instagram: The access_token provided is invalid.
    at e.parse (instafeed.js:2)
    at recent?access_token=XXXXXXXXX&count=10&callback=instafeedCache2a3640abf92dc8e8.parse:1
```

**Comment by jd4900** [comment]
I think this is the issue:

https://github.com/stevenschobert/instafeed.js/wiki/Managing-Access-Tokens

Going to deploy a Heroku app that will refresh the tokens.

**Comment by jd4900** [comment]
Heroku App: https://envision-token-agent.herokuapp.com/
