### ISSUE TITLE
Remove all references to old domain www.ubcchemecar.com

### ISSUE THREAD

**Issue by csianglim** [UBCEnvision/UBCEnvision.github.io#347]
We've stopped renewing the old domain at www.ubcchemecar.com and the page now points to something that's not very Chem-E-Car related.

To Do:

1. Fork old projects (2017 car, beer etc.) that you want to keep from the ubcchemecar github to the ubcenvision github. https://github.com/ubcchemecar

- As an example, I've forked the 2017 car site, which is now live at http://www.ubcenvision.com/2017/

2. Remove all references to ubcchemecar.com in the envision website.

**Comment by jd4900** [comment]
Commit ad4a788 removed all links associated with ubcchemecar.com. 

@mcassol can you go through the pages and decide which you want to be forked and added to the website as archive?

**Comment by csianglim** [comment]
@jd4900 beer page linking to beer.ubcchemecar.com https://github.com/UBCEnvision/UBCEnvision.github.io/search?q=ubcchemecar.com&unscoped_q=ubcchemecar.com

**Comment by jd4900** [comment]
All links have been removed
