### ISSUE TITLE
Unsupported Build Image When Deploying Changes to the Website

### ISSUE THREAD

**Issue by bhavyanagda47** [UBCEnvision/UBCEnvision.github.io#435]
UNSUPPORTED BUILD IMAGE

  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

All 4 unit tests by Netlify are failed

**Comment by bhavyanagda47** [comment]
Issue happens when a change is made on the website code i.e. updating a member's role. I am unable to merge my branch to the master branch.

**Comment by jd4900** [comment]
Relavant: https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by jd4900** [comment]
Just for CI/CD build. This was configured before GitHub actions was a thing. Disabling legacy CI/CD build and plan is to migrate to GitHub Actions.
